### ISSUE TITLE
Invoke commands in the README.md file are faulty

### ISSUE THREAD

**Issue by yeenab** [andela/wg-justice-league#6]
When we onboarded to the _wger_ project setting it up for development was a pain in the neck
One of the cause was these two commands:

```
$ invoke create_settings \
         --settings-path /home/wger/wger/settings.py \
         --database-path /home/wger/wger/database.sqlite
$ invoke bootstrap_wger \
         --settings-path /home/wger/wger/settings.py \
         --no-start-server
```

For the sake of future smooth development/local set up. I was suggesting they can be changed to these instead:

```
$ invoke create-settings \
         --settings-path /home/wger/settings.py \
         --database-path /home/wger/database.sqlite
$ invoke bootstrap-wger \
         --settings-path /home/wger/settings.py \
         --no-start-server
```

**Comment by lym** [comment]
This applies for all the *administration commands*. See the `$ invoke --list` command for details.

We should also mention that some people, for example @code-sleuth, have reported that the commands work, unmodified, for them.

**Comment by yeenab** [comment]
@lym what do you suggest?

Should we have both possibilities in the documentation or choose one method that works for all cases?

But I'd rather we choose what works always another reason being that it is even what the command `$ invoke --list` shows:

<img width="681" alt="screen shot 2018-01-19 at 18 04 58" src="https://user-images.githubusercontent.com/19430799/35156923-694c1fce-fd43-11e7-8145-2474aec940b4.png">

**Comment by lym** [comment]
I think we need help from @code-sleuth. If he can test and prove that the method the majority uses, "dashed commands" also works for him, then I guess we can cover only the "dashed commands". Otherwise I think it would be wrong for us to say that only the "dashed commands" work when in fact the "underscored commands" work for some folks, albeit the minority.
